Import('env')

exec_name = 'dxf_parser'

sources_src = [ Glob('../src/**/*.cpp'),
                Glob('../src/**/**/*.cpp') ]

sources_tst = [ Glob('*.cpp'), 
                Glob('**/*.cpp'), 
                Glob('**/**/*.cpp') ]

sources = sources_src + sources_tst

libs_src = ['boost_filesystem', 'boost_system', 'boost_program_options']

libs_tst = ['gtest']

libs = libs_src + libs_tst

env.Program(exec_name, sources, LIBS = libs)